# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://higherhangers.com
title: Higher Hangers
email: your-email@domain.com
author: Drew Cleaver
description: Invented in a college dorm room, Higher Hangers raise your clothes with their patented, space-saving, recessed hooks. Get control of your closet with Higher Hangers.
copyright: 'Copyright &copy; 2015 Higher Hangers. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
baseurl: "/hh"
fb-img: NakedHangerComparisonFB.jpg
nav-logo: nav_logo.png
baseurl: ""

#Live Website
#

#Localhost
destination:  /Users/Matt/Dropbox/01 higherhangers shared/_site

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: none #pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
